In [1]:
import numpy as np

In [24]:
# create a vector of integers from 0:8 and named it v

v = np.array([0,1,2,3,4,5,6,7,8])
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
# reshape v into a 3x3 matrix called M using np.reshape

M = np.reshape(v, (3,3))
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# repeat M into a 9x3 called C and use np.tile
C = np.tile(M, (3,1))
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Broadcast mutliple C with v called B

B =